services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST_WORKSPACE_PATH=${PWD}
    volumes:
      - .:/sible
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
