- name: A playbook that fails
  hosts: localhost
  tasks:
    - name: Print message
      debug:
        msg: "This is going to fail..."
        
    - name: Fail intentionally
      fail:
        msg: "This playbook failed on purpose!"
