---
- name: Check Secret Injection
  hosts: localhost
  connection: local
  tasks:
    - name: Print secret variable
      debug:
        msg: "The secret variable value is: {{ lookup('env', 'secret_variable') }}"
